CREATE TABLE IF NOT EXISTS booking_details (
  id INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  uid INT NOT NULL DEFAULT 0 COMMENT 'User id.',
  vid INT NOT NULL DEFAULT 0 COMMENT 'Vehicle id.',
  stime DATETIME DEFAULT NULL COMMENT 'Start time',
  s_lat DECIMAL(10,8) DEFAULT NULL COMMENT 'Start Lattitude.',
  s_lng DECIMAL(11,8) DEFAULT NULL COMMENT 'Start Longitude.',
  etime DATETIME DEFAULT NULL COMMENT 'End time',
  d_lat DECIMAL(10,8) DEFAULT NULL COMMENT 'End Lattitude.',
  d_lng DECIMAL(11,8) DEFAULT NULL COMMENT 'End Longitude.',
  bstatus TINYINT(3) NOT NULL DEFAULT 0 COMMENT 'Booking Status.',
  fare INT(11) NOT NULL DEFAULT 0 COMMENT 'Fare.',
  pstatus TINYINT(3) NOT NULL DEFAULT 0 COMMENT 'Payment Status.',
  added_by INT(11) NULL DEFAULT NULL,
  modified_by INT(11) NULL DEFAULT NULL,
  created_at DATETIME NULL DEFAULT NULL,
  modified_at DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id)
 );